Added Survey Manager and SRO Roles
ONSdigital/blaise-database pull request #70
Opened 2020-10-09 10:14 UTC by elthorne

2020-10-09 12:00 UTC, elthorne commented
This PR adds the following roles with subsequent features and access role management:

* Senior Research Officer. Can view most pages. Can edit Researcher roles only.
* Survey Manager. Can view most pages. Can edit Senior Research Officer and Researcher roles only.

See LU-7706 & LU-7707 fore more info.

Manually completed the following tests in https://dev-el-35-bsm.social-surveys.gcp.onsdigital.uk/:

As a DST_Tech role I can:
* Add/Edit Senior Research Officer (SRO) and Survey Manager roles

As a BDSS role I can:
* Add/Edit Senior Research Officer (SRO) and Survey Manager roles

As an SRO role I can:
* View the Interviewing, Sample file, Case Summary, CATI dashboard, Manage Users, Manage Surveys and Manage Field Periods pages
* Add/Edit Researcher roles only

As an Survey Manager role I can:
* View the Interviewing, Sample file, Case Summary, CATI dashboard, Manage Users, Manage Surveys and Manage Field Periods pages
* Add/Edit SRO and Researcher roles only

2020-10-12 10:19 UTC, matthewandrewpalmer requested changes
Working fine in sandbox, tested syncing to Blaise and that worked fine. One change suggested around user management.

2020-10-12 10:19 UTC, matthewandrewpalmer commented on alembic/versions/d04295661a60_003_add_new_roles.py
> +    survey_manager_manage_users = '["Survey_Manager", "Research"]'
Survey managers should not be able to able to manage Survey managers.
But should be able to manage Senior_Research_Officer's

```suggestion
    survey_manager_manage_users = '["Senior_Research_Officer", "Research"]'
```

2020-10-12 14:38 UTC, matthewandrewpalmer approved these changes
🦆 Looks good.

2020-10-12 14:39 UTC, merged